

years_load_early=[1993:2007];
years_load_early=[2007:2018];

TreeSetUp=TreeSetUp_2023_orca_heat_novert_test_NCAR_old;
% TreeSetUp=TreeSetUp_2023_orca_heat_novert_test_NCAR;
% [lonR,latR,mean_depthR,mean_depth_bndsR,yrR,ohcR]=load_heat_netcdf(years_load,TreeSetUp); 
% % % [lonRall,latRall,mean_depthRall,mean_depth_bndsRall,yrRall,ohcRall]=load_heat_netcdf_all_year(years_load_early,TreeSetUp); 
% % % % [lon,lat,yr,ohca_out,layer_bounds_NCAR_out]=load_heat_netcdf_NCAR_SMALL_fast(years_load,TreeSetUp);
% % % [lone,late,yre,ohca_oute,layer_bounds_NCAR_oute]=load_heat_netcdf_NCAR_SMALL_fast(years_load_early,TreeSetUp);

TreeSetUp=TreeSetUp_2023_orca_heat_novert_test_NCAR_paige_old;
% % % [lonRallpe,latRallpe,mean_depthRallpe,mean_depth_bndsRallpe,yrRallpe,ohcRallpe]=...
% % %     load_heat_netcdf_all_year(years_load_early,TreeSetUp); 
% [lonRallp,latRallp,mean_depthRallp,mean_depth_bndsRallp,yrRallp,ohcRallp]=...
%     load_heat_netcdf_all_year(years_load,TreeSetUp); 
%%
% 
% [amp_annual_total,phase_annual_total,amp_semi_total,phase_semi_total,...
% amp_third_total,phase_third_total,slope_total,mean_total,model_err_total]=...
% make_seasonal_cycle_comp_NCAR(yr,ohca_out);
% [amp_annual_totale,phase_annual_totale,amp_semi_totale,phase_semi_totale,...
% amp_third_totale,phase_third_totale,slope_totale,mean_totale,model_err_totale]=...
% make_seasonal_cycle_comp_NCAR(yre,ohca_oute);


%   [amp_annual_total_R,phase_annual_total_R,amp_semi_total_R,phase_semi_total_R,...
% amp_third_total_R,phase_third_total_R,slope_total_R,mean_total_R,model_err_total_R]=...
% % make_seasonal_cycle_comp_NCAR(yrR,ohcR);  
%    [amp_annual_total_Rall,phase_annual_total_Rall,amp_semi_total_Rall,phase_semi_total_Rall,...
% amp_third_total_Rall,phase_third_total_Rall,slope_total_Rall,mean_total_Rall,model_err_total_Rall]=...
% make_seasonal_cycle_comp_NCAR(yrRall,ohcRall);
% 
%     [amp_annual_total_Rallpe,phase_annual_total_Rallpe,amp_semi_total_Rallpe,phase_semi_total_Rallpe,...
% amp_third_total_Rallpe,phase_third_total_Rallpe,slope_total_Rallpe,mean_total_Rallpe,model_err_total_Rallpe]=...
% make_seasonal_cycle_comp_NCAR(yrRallpe,ohcRallpe);

%      [amp_annual_total_Rallp,phase_annual_total_Rallp,amp_semi_total_Rallp,phase_semi_total_Rallp,...
% amp_third_total_Rallp,phase_third_total_Rallp,slope_total_Rallp,mean_total_Rallp,model_err_total_Rallp]=...
% make_seasonal_cycle_comp_NCAR(yrRallp,ohcRallp);

%%


[amp_annual_2000e,phase_annual_2000e,amp_semi_2000e,phase_semi_2000e,...
amp_third_2000e,phase_third_2000e,slope_2000e,mean_2000e,model_fit_2000e]=...
make_seasonal_cycle_comp_NCAR_all(yre,ohca_oute);


  
   [amp_annual_2000_Rall,phase_annual_2000_Rall,amp_semi_2000_Rall,phase_semi_2000_Rall,...
amp_third_2000_Rall,phase_third_2000_Rall,slope_2000_Rall,mean_2000_Rall,model_fit_2000_Rall]=...
make_seasonal_cycle_comp_NCAR_all(yrRall,ohcRall);

    [amp_annual_2000_Rallpe,phase_annual_2000_Rallpe,amp_semi_2000_Rallpe,phase_semi_2000_Rallpe,...
amp_third_2000_Rallpe,phase_third_2000_Rallpe,slope_2000_Rallpe,mean_2000_Rallpe,model_fit_2000_Rallpe]=...
make_seasonal_cycle_comp_NCAR_all(yrRallpe,ohcRallpe);
